name             'le_rsyslog'
maintainer       'Joe Heung'
maintainer_email 'joe@joeheung.com'
license          'All rights reserved'
description      'Installs/Configures rsyslog to send to logentries.com'
long_description 'Installs/Configures rsyslog to send to logentries.com'
version          '0.1.4'
